[features]
seeds = true
skip-lint = false
[programs.devnet]
mint_stake = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://frosty-floral-wind.solana-devnet.quiknode.pro/fa3c7dec03be0b5335ff2905b342eedf94ada834/"
wallet = "/home/sixvxsh/Programming/blockchain/keys/mint-stake/mint-stake-ProgAuth.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
